version: '3.9'

services:
  app:
    image: puntpy:2.2
    ports:
      - 8844:8888
    working_dir: /home/wayneo
    volumes:
      - ./:/home/wayneo
      - DataVolume1:/home/wayneo/docker-share
    stdin_open: true
    tty: true  
    environment:
      - "TZ=Australia/Sydney"
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo
    ports:
      - 27444:27017    
    volumes:
      - punters-mongo-data:/data/db
      - ./.dump/mongo:/dump
    environment:
      - "TZ=Australia/Sydney"
    restart: always

  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4044:4000
    volumes:
      - ./:/srv/jekyll
      - DataVolume1:/home/docker-share
    environment:
      - "TZ=Australia/Sydney"
    restart: always

volumes:
  punters-mongo-data:
  DataVolume1:
    external: true