#!/bin/bash
# Download races for today

DOCKER=/usr/local/bin/docker
CURRENTDATE=`date`
FILENAME='run_jobs_bash'
BASEDIR='/Users/wayne/Documents/Projects/docker_apps/puntrz/.app/'
ALTDIR='/Users/wayne/Documents/Projects/docker_apps/mrwayneo/mrwayneo.github.io/'

echo `date`
$DOCKER exec mrwayneo_app_1 python3 .app/download.py
$DOCKER exec mrwayneo_app_1 python3 .app/upload.py
$DOCKER exec mrwayneo_app_1 python3 .app/library/magic.py
echo $CURRENTDATE "-->" `date`